name: elbaya_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  rflutter_alert: ^1.0.3
  google_maps_flutter: ^0.0.3
  flutter_google_places: ^0.1.4
  location: ^3.0.0
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.1.5
  firebase_database: ^3.0.7
  cloud_firestore: ^0.13.4+2
  shared_preferences: ^0.5.6+3
  random_string: ^2.0.1
  google_sign_in: ^4.4.3
  fluttertoast: ^3.1.3
  image_picker: ^0.6.6+1
  cached_network_image: ^2.0.0-rc.1
  intl: ^0.15.7
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.0
  photo_view: ^0.5.0
  
dependency_overrides:
  firebase_core: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logobaya.png
    - assets/splash.png
    - assets/notification.png
    - assets/calendar.png
    - assets/festival.png
    - assets/food.png
    - assets/map.png
    - assets/setting.png
    - assets/todo.png
    - assets/zoo.png
    - assets/rabbit.png
    - assets/hippo.png
    - assets/monkey.png
    - assets/correct.png
    - assets/fox.png
    - assets/hippo.png
    - assets/horse.png
    - assets/panda.png
    - assets/parrot.png
    - assets/question.png
    - assets/images/logo.png
    - assets/images/search_white.png
    - assets/images/send.png
    - assets/mimi1.gif
    - assets/mimi2.gif
    - assets/mimi3.gif
    - assets/mimi4.gif
    - assets/mimi5.gif
    - assets/mimi6.gif
    - assets/mimi7.gif
    - assets/mimi8.gif
    - assets/mimi9.gif
    - assets/img_not_available.jpeg
    - assets/sendd.png
    - assets/search.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
